version: "3.3"

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "ruby app.rb"
    ports:
      - "8080:4567"
    volumes:
      - "~/.bash_history:/.bash_history"
      - "./services/app:/usr/src/app:cached"
      - "/tmp:/tmp:delegated"
